### ISSUE TITLE
add native support for deploying docker stack

### ISSUE THREAD

**Issue by prabirshrestha** [hashicorp/waypoint#1068]
Currently deploy docker doesn't seem to work with docker compose files. 

```hcl
deploy {
    use "docker" {
        dockerfile = "./docker-compose.yml"
    }
}
```

Can we have support for `docker stack deploy -c ./docker-compose.yml`? Some might also want to pass `--prune` flag to prune services that are no longer referenced.

docker stack doesn't have an exclusive build task so we would need to have a noop build since waypoint requires build.

**Comment by evanphx** [comment]
@prabirshrestha Having waypoint know and understand docker-compose files doesn't fit well with the architecture of waypoint, because it hides too much about what is actually being deployed.

If you are looking to use docker compose in this way, you can use the `exec` plugin to template a docker-compose.yml file and execute `docker stack deploy`.
