### ISSUE TITLE
Nomad install job assigns random GRPC port, but UI seems unaware

### ISSUE THREAD

**Issue by nateberkopec** [hashicorp/waypoint#1245]
Install a waypoint server job to a Nomad cluster:

```
waypoint install -platform=nomad -nomad-dc=dc1 -accept-tos
```

Note the random GRPC port assignment in the job definition:

```
"DynamicPorts": [
            {
              "Label": "server",
              "Value": 0,
              "To": 9701,
              "HostNetwork": "default"
            }
          ]
```

However, after logging in to the Waypoint web UI, the "+ CLI" button in the top right assumes that the GRPC port is 9701:

```
waypoint context create \
    -server-addr=myaddr:9701
```

**Comment by gregone** [comment]
This will require some server work to return the advertised address (#1516)

**Comment by briancain** [comment]
We've updated the server install for Nomad to use a reserved port rather than a dynamic port. This should resolve the issue.

https://github.com/hashicorp/waypoint/blob/32cac33c6f0ba95b32a12a146b8d97ca404c4e25/internal/serverinstall/nomad.go#L874

I'm going to go ahead and close this, but if it's still an issue @gregone or @nateberkopec please feel free to let us know and we can re-open this! Thank you.
