### ISSUE TITLE
internal/state: Add Peek and Complete funcs to appOperation

### ISSUE THREAD

**Issue by briancain** [hashicorp/waypoint#1614]
**Is your feature request related to a problem? Please describe.**

To support running a queued poller for any kind of app related thing in Waypoint, `appOperation` state items should include a way to Peek at the _next_ thing to be polled, as well as a way to mark that thing as Completed.

**Describe the solution you'd like**

Update the `state/app_operation` implementation to include a generic way to `Peek` at the next item to be polled, as well as a way to mark that poll as `Complete`, similar to how this is handled in the `state/project` package. Then any app operation that has state storage that needs polling can simply use the app_operation interface to have a way to Peek and Complete.

In support of https://github.com/hashicorp/waypoint/issues/1612

**Comment by mitchellh** [comment]
There's a ton of ways to do this but this makes sense to make an operation pollable, but the interface should be separate of course because things like `Project` are not operations :) And things like `Project` may actually have multiple things they want to poll on (right now its just Git stuff but we could add another field to project).

I think you're thinking about this right but just noting. :)

**Comment by briancain** [comment]
I'm closing this. As mentioned in the linked PR, there isn't a clear use-case for this yet. Given we implemented application status polling already, I think we're safe to close this one out.
