### ISSUE TITLE
Automatically inject CHANGELOG in release pipeline using go-changelog

### ISSUE THREAD

**Issue by koesbong** [hashicorp/waypoint#1653]

**Comment by briancain** [comment]
My thoughts on this one is it would be good if we had either a review of the changelog being added, or some way to audit the changelog before it gets automatically committed since I know we've tended to highlight important features in releases. It could potentially just be a pre-release manual step or check before the pipeline starts.

**Comment by briancain** [comment]
I'm going to close this, as it's already covered as an issue in our release repo.
