### ISSUE TITLE
Add validations to all unauthenticated endpoints

### ISSUE THREAD

**Issue by evanphx** [hashicorp/waypoint#1700]
Related to #1682, we should validate all request values, but first let's make sure all the unauthenticated endpoints have these validations.

Validations like this: https://github.com/hashicorp/waypoint/blob/4f7174861053bb0bf51a17a26d56120867c5b7b1/internal/server/ptypes/workspace.go#L30-L37

**Comment by briancain** [comment]
For what it's worth it looks like the `GetVersionInfo` endpoint is pretty well handled:

First one is with some irrelevant request json in the body, and the second one is nothing at all (which is expected).

```
brian@localghost:static λ docker run -it --network host fullstorydev/grpcurl -d '{"application": {"application": "web", "project": "nginx-project"}}' --insecure -H "client-api-protocol: 1,1" -H "Authorization: `waypoint user token`" localhost:9701 hashicorp.waypoint.Waypoint/GetVersionInfo
Error invoking method "hashicorp.waypoint.Waypoint/GetVersionInfo": error getting request data: unknown field "application" in google.protobuf.Empty
brian@localghost:static λ docker run -it --network host fullstorydev/grpcurl --insecure -H "client-api-protocol: 1,1" -H "Authorization: `waypoint user token`" localhost:9701 hashicorp.waypoint.Waypoint/GetVersionInfo
{
  "info": {
    "api": {
      "current": 1,
      "minimum": 1
    },
    "entrypoint": {
      "current": 1,
      "minimum": 1
    },
    "version": "v0.5.0-461-gafa060c7"
  }
}
```

**Comment by briancain** [comment]
And the rest of the public API methods seem to be handled:

https://github.com/hashicorp/waypoint/blob/afa060c74bd320ed65a640567d53f73d25e1855a/internal/server/proto/server.proto#L14-L33

- GetVersionInfo (see above)
- ListOIDCAuthMethods
  + Same as GetVersionInfo, the request is an empty proto. So it handles irrelevant request body json similarly. And it's default is no request body
- GetOIDCAuthURL already has API validations
- CompleteOIDCAuth already has API validations.

I'm going to go ahead and close this since it seems to be handled. I'll take a stab at the authenticated endpoints next.
