### ISSUE TITLE
"This is an advanced approach."

### ISSUE THREAD

**Issue by dzrtc** [hashicorp/waypoint#1823]
**Is your feature request related to a problem? Please describe.**
I'm frustrated by the documentation because there is little information about running the tool from a shell environment.

The audience for folks setting up automated build pipelines isn't turned off by using the command-line, other Hashicorp products assume CLI knowledge, so it seems like a weird position to take to corral people into the UI.  I ssh into my infrastructure and don't plan on or need to use the UI. 

**Describe the solution you'd like**
I'd appreciate consolidated information about managing Waypoint operations from the terminal.  A Digital Ocean-style walk-through could fit on a single page.  There could be just one large warning on top, if that's necessary.

**Describe alternatives you've considered**
I've tried picking through all of the documentation to put together a coherent understanding of how to manage Waypoint remotely, but keep getting tripped up by slightly misleading examples (e.g. not including `-poll` in the Git Integration example).

**Additional Context**
If possible, I'd also like to understand whether this push towards web-based configuration represents a strategic shift in how Hashicorp thinks about tooling.

**Related Issues**
https://github.com/hashicorp/waypoint/issues/1744

**Comment by mitchellh** [comment]
I'll respond to the broad strategic questions, but I think another WP team member will get to you about the specifics on using a CLI to manage Waypoint and our docs gap there! 😄  I'm responding _only and specifically_ to this:

> If possible, I'd also like to understand whether this push towards web-based configuration represents a strategic shift in how Hashicorp thinks about tooling.

Kind of, but not at the expense of CLI support. There is nothing possible in the UI that isn't possible through the API or CLI. We are focusing on the UI for docs and guides to start because we've found through experience of our other products that (1) UIs bring more adoption than the CLI and (2) the UI usually has less footguns (i.e. less difficult to forget `-poll`). Additionally, as a resource constrained little team its hard to document _all the ways_ and our docs has obvious gaps. Issues like this help us prioritize and fill them.

That being said, we make sure every feature is properly represented in CLI form and the CLI experience continues to be an important aspect of our product design. If there are issues (i.e. maybe footgunning `-poll` could be avoided through some other behavior), then we'd like to address them 100%.

So, if we can turn this issue into actionable advice on how to improve the docs around specific use cases and perhaps how we can avoid footguns in some of our CLI flags and so on, we'll absolutely do it. Thanks for bringing it up. 😄

**Comment by briancain** [comment]
Hey there @dzrtc! Sorry to hear that you are frustrated. Based on your issue title, it sounds like you were trying to enable git polling on the command line, via https://www.waypointproject.io/docs/projects/git? We could do a better job of splitting out that page to cover both workflows.

Were you able to figure out how to turn on git polling in the CLI? If not, you can handle this like the following:

https://www.waypointproject.io/docs/waypoint-hcl/runner

* Setup a `data_source` in a runner stanza that's pointed at your git project: 

```hcl
runner {
  enabled = true

  poll {
    enabled = true
    interval = "30s"
  }

  data_source "git" {
    url  = "https://github.com/hashicorp/waypoint-examples.git"
    path = "docker/node-js"
  }
}
```

* Setup your runner for git

```
waypoint project apply \
   -data-source=git \
   -git-auth-type=ssh \
   -git-private-key-path=$HOME/.ssh/id_ed25519 \
   -git-url=git@github.com:hashicorp/waypoint-examples.git \
   -waypoint-hcl=waypoint.hcl \
   my-project
```

You could also enable polling with [waypoint project apply](https://www.waypointproject.io/commands/project-apply) and include the [poll specific flags](https://www.waypointproject.io/commands/project-apply#poll) when running the command.

If there are more examples of where you think we're missing clearer CLI docs, please let us know. Otherwise I'll leave this issue open to cover fixing up the git integration docs to improve covering the  [setup for git polling via the CLI](https://tip.waypointproject.io/docs/waypoint-hcl/runner#runner-stanza). Thanks!

**Comment by dzrtc** [comment]
@briancain Thank you for the support!  Your response could easily go directly into the documentation.
