### ISSUE TITLE
Docker build step does not support buildx

### ISSUE THREAD

**Issue by davidmytton** [hashicorp/waypoint#1881]
**Describe the bug**
[Docker buildx](https://docs.docker.com/desktop/multi-arch/) is needed to build for multiple CPU architectures e.g. different ARM architectures. Currently, the Waypoint Docker build step plugin executes `docker build` and cannot be configured to support `docker buildx`.

This may be a feature request but could also be a bug because executing `docker install buildx` [should alias](https://docs.docker.com/buildx/working-with-buildx/#set-buildx-as-the-default-builder) `docker build` to `docker buildx`. This should allow Waypoint to automatically support `buildx` with the additional `build_args` setting. However, even when this alias has been configured, Waypoint continues to execute `docker build`.

**Steps to Reproduce**
```shell
docker install buildx
waypoint build
```

**Expected behavior**
Waypoint executes using the `buildx` alias.

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI: v0.4.1 (4d5c838e)
* Waypoint Plugin: `docker`

**Comment by briancain** [comment]
Hey there @davidmytton - thanks for the feature request!

It's not as easy as aliasing a shell command for Waypoint, because we don't `exec` the docker CLI, but rather we use their [Go client to build images](https://pkg.go.dev/github.com/ph/moby/client#Client.ImageBuild) with our [Waypoint docker build plugin](https://github.com/hashicorp/waypoint/blob/86f5d261c3bbd221d6802c9b2d8330dcbc31078f/builtin/docker/builder.go#L299).

This _might_ work if we expose a `Platform` option in our docker builder plugin, which would get passed as an [image build option to the docker engine](https://pkg.go.dev/github.com/docker/docker/api/types#ImageBuildOptions) when building the image. However I don't know if `Platform` is a buildx option or something separate since there's not a codedoc there.

Anyway thanks for opening the issue!
