### ISSUE TITLE
Waypoint HCL file becomes garbled in the UI if saved on the server via UI

### ISSUE THREAD

**Issue by grahamhub** [hashicorp/waypoint#1923]
**Description:**

When copy/pasting HCL configuration into the server via the UI, if you go back to edit it later it gets garbled as seen in the screenshot:

![image](https://user-images.githubusercontent.com/18193667/126837815-c4897b14-3b3a-458a-ab18-09aeeeb58fb5.png)

I assume this is because the config is compressed when stored on the instance to save space, but doesn't get decompressed when viewing it. I know the environment settings are a bit behind, but I checked for issues and changelog stuff and couldn't find anything related to this issue - will update version and check again soon but in the middle of a sprint and it's not a pressing issue on our end so low priority and just wanted to bring awareness.

**Steps to Reproduce**

1. Initialize a new project with a context configured with a remote server and runner via the CLI (`waypoint init`) and then re-run the command to register it with the server so the project shows up in the UI.
2. Copy the `waypoint.hcl` configuration file that was generated (in our case it was still just the boilerplate) and paste it into the box in the UI when managing project settings.
3. Apply the configuration, then go back to project settings and it will be garbled

**Expected behavior**

I would expect to see the original HCL configuration I pasted within the text box so that I could edit it.

**Waypoint Platform Versions**

Waypoint:
CLI: v0.4.1 (4d5c838e)
Server: v0.4.0
Chrome: Version 91.0.4472.114 (Official Build) (64-bit)

Server and Runner are deployed on an EC2 Ubuntu 20.04 instance. 

In addition, our Server/Runner are running on a custom Docker image that we built since one of our plugins has some dependencies we needed to bake in - all other functionality works as expected so I don't expect our image to be the culprit.

Happy to look into this myself as well as I've become quite familiar with the codebase, but if anyone knows of where the culprit could be and point me in the right direction it would be helpful!

**Comment by jgwhite** [comment]
Hi Graham 👋

Many thanks for reporting this issue, great catch!

If you’d like to submit a PR, that would be fantastic. We’re here to help, every step of the way.

This appears to be an issue in the `ui` bit of the codebase.

Some notes:

1. The `waypoint_hcl` field [is declared as `bytes`](https://github.com/hashicorp/waypoint/blob/4e57bd155e5483c40d888b35753455acc921178b/internal/server/proto/server.proto#L470) so you’re absolutely right, the UI isn’t quite accounting for that.
2. `grpc-web` doesn’t automatically deserialize a `bytes` field into a string when using `toObject()` (which makes sense, as `bytes` could be any data). We just happen to know that it’ll be a utf-8 string in this case.
3. We emit the value into the UI in the template [`project-repository-settings.hbs`](https://github.com/hashicorp/waypoint/blob/730b63c1dc4be4a4727dfe76328db5f7b9b78669/ui/app/components/app-form/project-repository-settings.hbs#L220)
4. That template is backed by [`project-repository-settings.ts`](https://github.com/hashicorp/waypoint/blob/4e57bd155e5483c40d888b35753455acc921178b/ui/app/components/app-form/project-repository-settings.ts)
5. We seem to currently [write to `project.waypointHcl` as the user inputs text in that textarea](https://github.com/hashicorp/waypoint/blob/4e57bd155e5483c40d888b35753455acc921178b/ui/app/components/app-form/project-repository-settings.hbs#L222), which means `project.waypointHcl` flips from bytes-as-base64 to a regular string as soon as input occurs. This could get a little confusing, so it might be worth reworking the `on "input"` behavior so that the type of `project.waypointHcl` is more predictable.

Let us know what you think. If you don’t have the bandwidth to submit a PR right now, no problem at all — this report is already a terrific contribution to the project.

**Comment by grahamhub** [comment]
@jgwhite thanks for the detailed breakdown! I should have some spare time this week / weekend to take a look at it

**Comment by jgwhite** [comment]
It looks like `privateKeyPem` is also a `bytes` field and also suffers this same bug. You may want to tackle that using the same approach.

Again, we’re here to support you. Let us know how you get on.

**Comment by grahamhub** [comment]
Thanks Jamie!

Took a deeper look into all those pieces you mentioned, and I'm still a bit fuzzy on the flow of saving the file since I've not used Handlebars very much.

From what I understand, this `on "input"` expression sets the [attribute `waypointHcl` defined on the class](https://github.com/hashicorp/waypoint/blob/4e57bd155e5483c40d888b35753455acc921178b/ui/app/components/app-form/project-repository-settings.ts#L41) to be the value in the textarea (`target.value`). Then, when the user clicks "Apply", it will trigger [the `saveSettings` action](https://github.com/hashicorp/waypoint/blob/4e57bd155e5483c40d888b35753455acc921178b/ui/app/components/app-form/project-repository-settings.ts#L196) - this will then take the input and encode it into a `Uint8Array`, eventually being written to the file during the project upsert.

Another assumption that I'd like to confirm - I dug around the `waypoint-server` and couldn't find any actual HCL files. The configuration is stored in `data/data.db` then, yes?

And finally, when I decode the value currently in the textarea via `atob(IyBU...Q==)` I do get the HCL configuration. Would it make sense to do this decoding within the [constructor, similar to how git settings are restored?](https://github.com/hashicorp/waypoint/blob/4e57bd155e5483c40d888b35753455acc921178b/ui/app/components/app-form/project-repository-settings.ts#L96). If there were an action, something like `parseHcl` or `decodeBase64`, that deserialized the incoming bytes, would that be reflected in the UI since it would be part of the constructor?

Oh, and how would I run the build process to have these UI changes reflect in the `waypoint:dev` server image for testing? Is it just the same build steps outlined in the contributing guide or are there extra steps I need to take (like compiling TS or running a Webpack build)?

Alright, I think that covers all my bases 😅 I may still be missing a piece here or there with my mental model, haven't worked with TS or HBS with this many moving parts before

**Comment by jgwhite** [comment]
> From what I understand, this `on "input"` expression sets the [attribute `waypointHcl` defined on the class](https://github.com/hashicorp/waypoint/blob/4e57bd155e5483c40d888b35753455acc921178b/ui/app/components/app-form/project-repository-settings.ts#L41) to be the value in the textarea (`target.value`). Then, when the user clicks "Apply", it will trigger [the `saveSettings` action](https://github.com/hashicorp/waypoint/blob/4e57bd155e5483c40d888b35753455acc921178b/ui/app/components/app-form/project-repository-settings.ts#L196) - this will then take the input and encode it into a `Uint8Array`, eventually being written to the file during the project upsert.

That is exactly right 👍 

> Another assumption that I'd like to confirm - I dug around the `waypoint-server` and couldn't find any actual HCL files. The configuration is stored in `data/data.db` then, yes?

Also exactly correct. The `waypoint.hcl` can live either in the project’s source repo, or remotely in the database (stored on disk as `data.db`, as you say).

> And finally, when I decode the value currently in the textarea via `atob(IyBU...Q==)` I do get the HCL configuration. Would it make sense to do this decoding within the [constructor, similar to how git settings are restored?](https://github.com/hashicorp/waypoint/blob/4e57bd155e5483c40d888b35753455acc921178b/ui/app/components/app-form/project-repository-settings.ts#L96). If there were an action, something like `parseHcl` or `decodeBase64`, that deserialized the incoming bytes, would that be reflected in the UI since it would be part of the constructor?

Yep, that’s seems like a workable approach. We definitely need to `atob` somewhere along the line and in the constructor should do the trick.

Another alternative is to use a computed property:

```ts
get decodedWaypointHcl(): string {
  return atob(this.project.waypointHcl);
}
```

Or you could define a [helper](https://guides.emberjs.com/release/components/helper-functions/) such that we decode the value at the very last moment:

```hbs
value={{atob this.project.waypointHcl}}
```

Something else that might be helpful on your quest (and that I only learned this week) is that the `project.setWaypointHcl` protobuf method accepts either a `Uint8Array` *or* a `string` containing base64 encoded data. This is true for all fields of type `bytes`.

We call it here:

https://github.com/hashicorp/waypoint/blob/0ef2c3c6cdec5a6b4dbedcce2095695dc9f2dc44/ui/app/components/app-form/project-repository-settings.ts#L247-L251

Abstractly, this means either of the following works:

```ts
// Assuming `someHCL` is a plain string of HCL
project.setWaypointHcl(new TextEncoder().encode(someHCL));
project.setWaypointHcl(btoa(someHCL));
```

This is useful to know because if the value is already in base64 then we needn’t do any further conversion.

> Oh, and how would I run the build process to have these UI changes reflect in the `waypoint:dev` server image for testing? Is it just the same build steps outlined in the contributing guide or are there extra steps I need to take (like compiling TS or running a Webpack build)?

There are a couple of extra preamble steps and we should do a better job of document these. It goes like this:

1. Build the UI:
   ```shell
   (cd ui && make)
   ```
2. bindata the compiled UI assets into `internal/server/gen/bindata_ui.go`:
   ```shell
   make static-assets
   ```
3. Build the `waypoint:dev` image:
   ```shell
   make docker/server
   ```

> Alright, I think that covers all my bases 😅 I may still be missing a piece here or there with my mental model, haven't worked with TS or HBS with this many moving parts before

Based on these questions, I’d say you have an excellent grasp of all the moving pieces here. You should be all set. Can’t wait to see the PR!

P.S. I’m out on vacation next week, but the rest of the team will be around to help out.

**Comment by grahamhub** [comment]
Thank you for the wonderful guidance, Jamie! I have a much clearer path forward now, should have something soon :)
