### ISSUE TITLE
Gitlab CI/CD Integration fails with Remote Runner

### ISSUE THREAD

**Issue by pilayar76** [hashicorp/waypoint#1988]
**Describe the bug**
While integrating Waypoint in Gitlab CI/CD to deploy cloud run service, getting below error

 ```
! Unable to list regions for project xxx: googleapi: Error 403:
  Request had insufficient authentication scopes.
  More details:
  Reason: insufficientPermissions, Message: Insufficient Permission
```

**Steps to Reproduce**
Integrate the Waypoint with Gitlab CI/CD

Waypoint.hcl

```
project = "sample"

app "e2eapi" {
  labels = {
    "service" = "e2eapi",
    "env"     = "production"
  }

  build {
    use "pack" {}

    registry {
      use "docker" {
        image = "xxxx"
        tag   = "latest"
      }
    }
  }

  deploy {
    use "google-cloud-run" {
      project         = "xxxx"
      location        = "asia-south1"
      unauthenticated = true
      port            = 3002

      capacity {
        memory                     = 128
        cpu_count                  = 2
        max_requests_per_container = 100
        request_timeout            = 300
      }

      auto_scaling {
        max = 10
      }
    }
  }

  release {
    use "google-cloud-run" {}
  }
}
```

**Expected behavior**
waypoint deploy should run successfully.

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: 0.4.2
* Waypoint Server Platform and Version: (like `docker`, `nomad`, `kubernetes`) Docker
* Waypoint Plugin: (like `aws/ecs`, `pack`, `azure`) GCP Cloud Run

**Additional context**

**Comment by pilayar76** [comment]
<img width="157" alt="image" src="https://user-images.githubusercontent.com/32598510/128272276-a6ca4fae-11a2-4ff3-a6b0-5da3e0579339.png">

Service Account which I am using  has almost all the permissions

**Comment by izaaklauer** [comment]
Hi @pilayar76,

Have you attached the service account to your waypoint runner? It looks like the problem here is that gitlab is triggering a deployment, which is executed by the waypoint remote runner, which in turn doesn't have the credentials necessary to deploy to google cloud. 

To get a remote runner with credentials to access google cloud, you will likely need to run your own runner, in an environment with google cloud credentials available, instead of using the runner that comes automatically with `waypoint install` (which doesn't have any google credentials included). See https://www.waypointproject.io/commands/runner-agent for instructions on how to run your own remote runner.

**Comment by pilayar76** [comment]
Hi @izaaklauer  - Thanks for the reply. 

this is my gitlab script and I thing I am using local runner not the remote one.

`
waypoint:
  # GitLab created images, which basically rewraps HashiCorp's officially released binaries and may not match HashiCorp's checksums, See https://gitlab.com/gitlab-org/waypoint-images for more details about what goes into the images.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    WAYPOINT_VERSION: '0.4.2'
    WAYPOINT_SERVER_ADDR: ''
    WAYPOINT_SERVER_TOKEN: ''
    WAYPOINT_SERVER_TLS: '1'
    WAYPOINT_SERVER_TLS_SKIP_VERIFY: '1'
  before_script:
    # Install CA certs, openssl to https downloads, python for gcloud sdk
    - apk add --update make ca-certificates openssl python3
    - update-ca-certificates
    # Download and install Google Cloud SDK
    - wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz
    - tar zxvf google-cloud-sdk.tar.gz && ./google-cloud-sdk/install.sh --quiet --usage-reporting=false --path-update=true
    - PATH="google-cloud-sdk/bin:${PATH}"
    - gcloud --quiet components update
    - gcloud components install beta

    # Authenticate using the service account stored here: https://gitlab.com/groups/{YOUR_GITLAB_PROJECT}/-/settings/ci_cd
    - echo $GCP_SERVICE_KEY > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - sh scripts/docker.sh
    - gcloud auth list
    - gcloud auth configure-docker
  script:
    - wget -q -O /tmp/waypoint.zip https://releases.hashicorp.com/waypoint/${WAYPOINT_VERSION}/waypoint_${WAYPOINT_VERSION}_linux_amd64.zip
    - unzip -d /usr/local/bin /tmp/waypoint.zip
    - rm -rf /tmp/waypoint*
    - waypoint init
    - waypoint build
    - env
    - waypoint deploy
    - waypoint release
`

**Comment by izaaklauer** [comment]
Ah, gotcha. It looks like the `waypoint deploy` process isn't seeing your google credentials. Running `google auth configure-docker` won't work for you here, because you're not running waypoint inside docker - you're running it directly. I think setting a `GOOGLE_APPLICATION_CREDENTIAL=/path/to/your/gcloud-service-key.json` env var might do the trick for you.

**Comment by pilayar76** [comment]
@izaaklauer  - That was a life saver. Thanks alot. It works perfectly now. I am happy to close this issue.
