### ISSUE TITLE
Allow input variables to be marked as 'sensitive'

### ISSUE THREAD

**Issue by briancain** [hashicorp/waypoint#2136]
**Is your feature request related to a problem? Please describe.**

When configuring waypoint with any kind of sensitive variable, like a container registry password or API token, Waypoint should let users mark that variable as sensitive. Then in the case where we show the variable in the logs, or any other place (like the UI), we can know to omit the value so we don't leak sensitive information like passwords or API tokens. We can also use this option to ensure we aren't storing secrets in plaintext too.

**Describe the solution you'd like**

Something similar to how other products that use input variables use! I'm not super familiar with how they handle it, but it syntactically it should match those. We should also ensure if a variable is marked as sensitive, it's stored properly.

**Describe alternatives you've considered**

**Explain any additional use-cases**

Any API tokens that might be required for future plugins too!

**Additional context**

**Comment by apparentlymart** [comment]
The way this works in Terraform is unfortunately a rather gnarly cross-cutting concern: we [mark](https://github.com/zclconf/go-cty/blob/main/docs/marks.md) values as sensitive as they pass through a `variable` declaration with `sensitive = true`, and then every downstream of use of that variable needs to be careful to preserve the sensitive marking in whatever way makes sense for the semantics of that operation.

Taking a similar approach would mean you could benefit from the work the Terraform team already did to thread sensitive value handling through HCL, but we also had to update quite a few operations within the Terraform runtime itself. I expect there'd be some comparable work to do within Waypoint-specific code too, in order to get sensitivity to propagate correctly throughout. (Basically, any time you directly or indirectly use one of the `cty.Value` methods whose return type isn't also a `cty.Value`, and so `cty` can't propagate the sensitivity for you automatically.)

This idea of "marks" also presents problems for serialized values, because e.g. there's no built-in syntax for marking a value as "sensitive" in JSON. Terraform deals with this by remembering sensitive value paths in a sidecar data structure and then reapplying them after deserializing.

The above complexity is, of course, necessary only if you have the requirement that sensitivity should propagate through expressions into derived values. For example, if `variable "number"` is marked as sensitive, making it so that `var.number + 2` would also produce a sensitive result. I don't know if you have that requirement; if not, your implementation would be considerably simpler, though the benefit of implementing it might then be smaller.
