### ISSUE TITLE
Waypoint to deploy in multiple nomad cluster

### ISSUE THREAD

**Issue by thatsk** [hashicorp/waypoint#2175]
**Is your feature request related to a problem? Please describe.**
As we know waypoint integrates with nomads. So I wanted to know if we want to deploy from dev nomad environment, staging and then production environment nomad.

**Describe the solution you'd like**
How we deploy the application from build to a different environment in nomamd.Is there a way we promote artifacts to a different environment?

**Describe alternatives you've considered**
There is a tool in the market called gocd. I am thinking to replace that with waypoint and nomad.
https://www.gocd.org/
are we handling it the same way?

**Comment by evanphx** [comment]
Hi @thatsk! We're in the midst of working on some features that should make it possible for you to do this. Right now, we're working on the ability for waypoint workspaces to hold variables themselves (in a way), allowing a single waypoint configuration to adapt to dev/staging/prod.

One thing that we're still thinking about is how to handle promotion. That will come in time, but we don't yet have anything sorted out for it.

**Comment by thatsk** [comment]
How about promoting the artifact to different environments??

**Comment by briancain** [comment]
Hey @thatsk! We support this now with the latest release of Waypoint via Runner Targeting. You should be able to use various runner profiles to target separate nomad clusters for deployments. https://tip.waypointproject.io/docs/runner#runner-targeting

We do agree that artifact promotion to different environments is important and we don't have a good answer for that yet but are working on making that happen with Waypoint soon.

I'm going to go ahead and close this issue since the original request is possible now with runner targeting.

**Comment by thatsk** [comment]
so should we open new issue for artifact promotion like container promotion and different artifacts
?

**Comment by briancain** [comment]
@thatsk - We are currently working on that with Waypoints Pipelines feature. But feel free to open an issue with some of the requirements you might have and we can track it on GitHub.
