### ISSUE TITLE
ECS Releasing results in downtime due to lack of deployment warming

### ISSUE THREAD

**Issue by evanphx** [hashicorp/waypoint#2187]
Currently, performing an ECS release can result in downtime because the new deployment being targeting is not yet running, and so shunting traffic to it results in the application experiencing downtime.

Perhaps Waypoint should check the status of a deployment before manipulating the release.

**Comment by izaaklauer** [comment]
I think the problem here is that for ecs, neither the deploy or release plugins check that the target group has active targets before switching it take all traffic from the alb.

I think you could repro this by making an app that takes more than a few seconds to start up (or for repo convenience, never starts up), and then run `waypoint up`. In the deploy phase, waypoint will create the service, task, and target group, and add the target group to the ALB with 0% traffic. Then in the release phase, waypoint will toggle the alb to forward 100% of the traffic to the new task, despite the fact that it has no healthy targets.

I think we definitely need to verify that the target group has healthy targets before allowing it to be released. I think the simplest thing for now is to require that 100% of the targets are healthy for a deployment before allowing a release. We can think about a `release -force` option later to override that if someone wants to release to a partially-healthy deployment.

I think we should also put information about target health in the status checks for both deployments and releases (like the alb releaser [here](https://github.com/hashicorp/waypoint/blob/38d713bcbcda7e58d21413bab376716d6c6a3ebd/builtin/aws/alb/releaser.go#L845))


Another related question I have in thinking about this: when running `waypoint up` against ecs, it looks like it's common for the deployment's status check to return PARTIAL health, and then for the the release to go ahead and release it anyway? It seems like this could be another guard: during `waypoint release`, we could check the deployment's most recent status report (and maybe run a new status report if there isn't a recent one). If it's not healthy, maybe we re-run a status report, and if it's still unhealthy, we refuse to release.
