### ISSUE TITLE
Improve performance of UI_ListDeployments and UI_ListReleases

### ISSUE THREAD

**Issue by izaaklauer** [hashicorp/waypoint#2304]
These new endpoints are not especially performant. They have been observed to take >10s response time with ~50 deployments with a wp server on a t3-micro, and ~1s with a small project on a developer laptop:

![image](https://user-images.githubusercontent.com/8404559/133332725-3732e3c9-5a19-48e6-9809-e7acbfdbc055.png)

There is some low-hanging fruit here, but will require adding support for more performant queries to our state package: https://github.com/hashicorp/waypoint/blob/f75353c7ca810885c594d37b51bdef9ef6d77c2b/internal/server/singleprocess/service_ui_deploy.go#L27-L28

**Comment by evanphx** [comment]
The issue is that this function is O(MN^2), where M == number of status reports and N == number of deployments. The solution is to add a state.StatusReportForDeployment. Doing so requires adding the ability to add additional memdb indexes for appOperations, so that the StatusReportForDeployment code can use memdb.First directly on the index that of the statusreport table to the deployment id.

**Comment by briancain** [comment]
Forgot to follow up here, but my research shows that the slow part in this endpoint is directly related to Deployments/Releases rather than status reports. I had a single deployment with over 4000 status reports and the endpoint only slowed down by 0.2 seconds. However, when I cranked up the deployments and releases, the request slowed down by almost 2.5 seconds.

We could try to speed up grabbing deployments/releases, however I generally don't think we are using this endpoint to query for every single deployment or release very often. The UI and CLI both trim their requests to something small, like ~5 deployments/releases I believe. I didn't notice a major slow down until I had about 80 deployments and releases to list.

**Comment by siccous** [comment]
This issue still persist and makes Waypoint UI nearly useless for me. I have few apps with 150+ exec deployments and it never ever completes loading the deployments from API (it starts to load in loop because of autorefresh I guess).

Is there at least a way how to clear old destroyed deployments? Even if I prune all past deployments then the UI still loads all of them.

**Comment by jgwhite** [comment]
@briancain and I discussed this and we think as a temporary measure we could limit the number of deployments requested to 50. We should still improve the performance of these methods, and pursue true pagination in the API, but the 50 limit will hopefully make Waypoint UI usable in cases like this.

**Comment by lukemelia** [comment]
Is there any immediate workaround for this, such as trimming the recorded deployments somehow?

**Comment by briancain** [comment]
Some extra context here - we think that when [the UI Deploy/Release bundle calls](https://github.com/hashicorp/waypoint/blob/61dafdf940cd53a85b931a956fb0da4cc07a0dfd/internal/server/singleprocess/service_ui_deploy.go#L87-L110) `ListHostnames`, it makes an API call to our external service Horizon for each deployment. We're going to try to optimize this and make it better and see if this resolves the slow-down here. I will be taking this on this week and will report my findings here and or open a pull request! Thanks everyone.

**Comment by briancain** [comment]
Hey all - it looks like the message I wrote yesterday was correct. Fixing the endpoint to only lookup the hostname once for crafting the `deployUrl` field greatly improved the performance of this endpoint. Look for a fix in the PR mentioned, and we will make sure this gets out in the next minor release of Waypoint! Thank you all ❤️
