### ISSUE TITLE
Be able to deploy the same repo from different branches

### ISSUE THREAD

**Issue by nsurleraux-railnova** [hashicorp/waypoint#3146]
**Is your feature request related to a problem? Please describe.**
We have several environments for our apps (development, testing, production), each based on a different branch of our repository.

**Describe the solution you'd like**
Be able to specify for each app or with a variable the branch to deploy from.

**Describe alternatives you've considered**
Tried runner configuration with variables, cannot use that because `waypoint init -update` cannot take variables.

**Comment by xiaolin-ninja** [comment]
Hi @nsurleraux-railnova, we are tracking the issue here https://github.com/hashicorp/waypoint/issues/1665 and this is definitely on our to-do list. I am closing this issue since this is a duplicate, if you have any more context, please feel free to drop it in the other issue since that's where we are tracking this feature.
