### ISSUE TITLE
Deprecation warning is a hard failure

### ISSUE THREAD

**Issue by krantzinator** [hashicorp/waypoint#3601]
**Describe the bug**
The deprecation error for multi-app configs should be a warning, not a full error.

**Steps to Reproduce**
Run `waypoint up` with >1 app in a waypoint.hcl

**Expected behavior**
The warning should allow current multi-app behavior to continue.

* Waypoint CLI Version: 0.9.0

**Additional context**
[Discuss conversation](https://discuss.hashicorp.com/t/deprecating-projects-or-how-i-learned-to-love-apps/40888/8)

**Comment by briancain** [comment]
If I remember right, the current issue is that the config `Validate()` function returns that `Warning`/`Error` struct, but every where that calls `Validate()` just treats warnings and errors only as an `error`. We could technically go into each place in Waypoint that validates a config and look to see if there are any Warnings and print those, otherwise raise an error. It would be more ideal if we could treat the Warning printing in the config validate class itself in a single place, so all upstream callers would get it for free.
