### ISSUE TITLE
waypoint server run vs. waypoint install

### ISSUE THREAD

**Issue by skitsanos** [hashicorp/waypoint#3643]
Hi,

I have tried to follow instructions on a running server with `waypoint server run` and run into a strange issue: 
- UI and gRPC Ports are accessible from public IP if run `waypoint install`,
- ports are NOT accessible if I run `waypoint server run`.

unit file for `waypoint.service` is like this:

```
[Unit]
Description=Waypoint Server
After=syslog.target network-online.target docker.service
Requires=network.target
BindsTo=docker.service
ReloadPropagatedFrom=docker.service

[Service]
ExecStart=waypoint server run -accept-tos -listen-http=0.0.0.0:9702 -listen-grpc=0.0.0.0:9701 -db /waypoint_data/db -advertise-tls-skip-verify

[Install]
WantedBy=default.target
```

Logs are clean:

```
Aug 05 08:15:20 waypoint-dev systemd[1]: Started Waypoint Server.
Aug 05 08:15:20 waypoint-dev waypoint[2632]: » Server configuration:
Aug 05 08:15:20 waypoint-dev waypoint[2632]:              DB Path: /waypoint_data/db
Aug 05 08:15:20 waypoint-dev waypoint[2632]:         gRPC Address: [::]:9701
Aug 05 08:15:20 waypoint-dev waypoint[2632]:         HTTP Address: [::]:9702
Aug 05 08:15:20 waypoint-dev waypoint[2632]:        Auth Required: yes
Aug 05 08:15:20 waypoint-dev waypoint[2632]:   Browser UI Enabled: yes
Aug 05 08:15:20 waypoint-dev waypoint[2632]:          URL Service: api.waypoint.run:443 (account: guest)
Aug 05 08:15:20 waypoint-dev waypoint[2632]: » Server logs:
Aug 05 08:15:20 waypoint-dev waypoint[2632]: 2022-08-05T08:15:20.709Z [INFO]  waypoint.server: starting built-in server: addr=[::]:9701
Aug 05 08:15:20 waypoint-dev waypoint[2632]: 2022-08-05T08:15:20.709Z [INFO]  waypoint.server.http: starting HTTP server: ln=[::]:9702 addr=[::]:9702
Aug 05 08:15:20 waypoint-dev waypoint[2632]: 2022-08-05T08:15:20.709Z [INFO]  waypoint.server.grpc: starting gRPC server: addr=[::]:9701
```

Any hint on why it could not be accessible from public IP on the `waypoint server run` but worked with `waypoint install` ?

**Comment by briancain** [comment]
Hey there @skitsanos - Can you go into more detail about how you were checking that running `waypoint server run` is not accessible? Are you trying the waypoint CLI and it's not working, telnet directly, or something else? For example, testing your access to the server....

> telnet 0.0.0.0 9702

**Comment by skitsanos** [comment]
when I ssh on the instance (btw, it is on Oracle Cloud), where I can curl just fine on 0.0.0.0:9701/9702. what I found strange is that if I run waypoint install, I can see it both locally with curl and from 'outside', but if I run it as systemd service, the 'outside' part is gone...

took a VPS today, did all the same steps with systemd ... and it works just fine. Now it makes me think that it has something to do with actual Oracle...

btw, we need something to do with the documentation for Waypoint... When your un things locally and see it working so smooth and nice and then you wanna go 'real world' and hit the massive wall of the absence of documentation on how to run things on your own bare metal/vps... I am comparing it to how nicely documented HCP Vault is, It makes me cry...

**Comment by briancain** [comment]
> took a VPS today, did all the same steps with systemd ... and it works just fine. Now it makes me think that it has something to do with actual Oracle...

That makes sense. When you install to one of our expected platforms via `waypoint install` networking is often handled by that platform (i.e. docker or kubernetes). If you're running Waypoint directly with `waypoint server run` you'll need to make sure that process is exposed on your virtual machine or bare metal computer so it can be accessed outside of that machine.

> btw, we need something to do with the documentation for Waypoint... When your un things locally and see it working so smooth and nice and then you wanna go 'real world' and hit the massive wall of the absence of documentation on how to run things on your own bare metal/vps... I am comparing it to how nicely documented HCP Vault is, It makes me cry...

Currently our expectation is the majority of our users who want to deploy Waypoint server in the real world will do so via our provided container image `hashicorp/waypoint:latest` inside container schedulers such as Kubernetes, Nomad, or ECS rather than running it directly with `waypoint server run`. Running the server directly is totally a valid way to run Waypoint server, just not one of our expected main pathways to do so.

Vault is a product that has been around a while, so they've had time to build up their documentation. Waypoint is still a fairly new open source tool, so sorry that we don't have as much documentation. We are working to write learn guides and docs for areas of Waypoint that we believe people will need to understand for using Waypoint in production. If you are interested in specific documentation that we don't have feel free to open an issue to request it or if you'd like you are welcome to provide some documentation too!

Since it sounds like your original issue was resolved with Oracle Cloud, I'm going to go ahead and close this. Thank you.
