### ISSUE TITLE
Packer builder plugin

### ISSUE THREAD

**Issue by gordonbondon** [hashicorp/waypoint#518]
Packer supports multiple output formats and it would be great to be able to use it inside `waypoint`. Currently, it would be able to integrate with `aws-ec2` deploy plugin.

Possible config:
```hcl
build {
  use "packer" {
    template = "./build.pkr.hcl"
    var_file = "./variables.json"
    var = {
      region = "us-east-1"
    }
    except = ...
    ...
  }
}
```

`waypoint` should be able to inject [`manifest`](https://www.packer.io/docs/post-processors/manifest) post-processor and grab required artefact ids from its output.

**Comment by mitchellh** [comment]
Yes, we wanted to include this for 0.1 actually and didn't have time to make it in. We'd love a Packer plugin!

**Comment by evanphx** [comment]
@gordonbondon you're right on the nose, I had intended to use a pack build plugin with the aws-ec2 plugin suite but ran out of time for 0.1. That's why the aws-ami builder got slotted in there, so folks could run packer before waypoint and then pickup the ami to use with waypoint.

And as @mitchellh said, we absolutely want a packer plugin!

**Comment by orenmazor** [comment]
just following up, any idea of when this could be available? :)

**Comment by evanphx** [comment]
@orenmazor what kinds of things do you want to build with packer?

**Comment by orenmazor** [comment]
good question :) 

in my case, I have a packer template for a docker container that I'd like to deploy. I could convert this to a dockerfile, but then that makes my provisioner steps a little messier.

**Comment by evanphx** [comment]
@orenmazor Gotcha, that makes sense. One reason we haven't yet supported packer is it's pretty complicated as it's output doesn't represent a singular build artifact type.

If we make the plugin more like this:
```
build {
  use "packer-docker" {
     template = "packer.hcl"
  }
}
```

with the `packer-docker` build plugin expecting to see packer generate a docker image with that information, it should be much more doable. I'll chat with the team about approaching the problem this way.

**Comment by orenmazor** [comment]
I appreciate that Evan! Honestly, I assumed something as such. Especially when I was wondering why there is no exec plug-in for the build step :)

**Comment by orenmazor** [comment]
@evanphx one thing that I just thought about: you could also consider having something like the deploy-exec plugin, but build-exec. we'd provide a command and there'd be an agreed "this creates a docker image" element to it. 

mind, I haven't looked at the code so this could be insanely impossible. but if it is, this might be simpler than working with packer (at this point, at least), and it would give folks the ability to use custom docker builders.

```
use "custom-docker-artifact" {
    command = []
    resulting_image = foo
    resulting_tag = bar
}
```

< /poorly thought out brainstorm >

**Comment by RichiCoder1** [comment]
Packer w/ Amazon AMI + Amazon EC2 since a natural one too considering there's already EC2 support.

**Comment by briancain** [comment]
Hey there Waypoint readers! As of today, we have a Packer integration with config sourcers to read from an existing container. At the moment, we don't have plans for a full packer plugin integration given how many different kinds of plugins Packer supports. Realistically we would probably want a packer-<feature> plugin rather than a overall Packer plugin. Hope that makes sense, thank you!
