### ISSUE TITLE
waypoint reinstall/upgrade

### ISSUE THREAD

**Issue by cpswan** [hashicorp/waypoint#612]
**Is your feature request related to a problem? Please describe.**
If I run `waypoint install -platform=docker -accept-tos` where there is an existing install then I see:

```
⚠️ Detected existing waypoint server
! Error getting the initial token: server is already bootstrapped

  The Waypoint server has been deployed, but due to this error we were
  unable to automatically configure the local CLI or the Waypoint server
  advertise address. You must do this manually using "waypoint context"
  and "waypoint server config-set".
```

But there are time when I may want to overwrite or upgrade the existing install e.g. when I've just downloaded a newer version of the waypoint binary and the waypoint server docker image.

**Describe the solution you'd like**
When detecting new binary and docker image waypoint should ask:

```
Detected existing waypoint server, do you want to upgrade (y/n)?
```

Otherwise:

```
Detected existing waypoint server, do you want to reinstall (y/n)?
```

**Describe alternatives you've considered**
I've been manually killing and removing docker containers running waypoint server then running `waypoint install -platform=docker -accept-tos` then using `waypoint context` and `waypoint server config-set`. Seems like a lot of yak shaving that waypoint could do for me.

**Comment by mitchellh** [comment]
We at the very least want a stop command which is #479 (which would include "Uninstall" in my mind). 

We're not sure yet on upgrades and so on but I'll keep this open as we think about it.

**Comment by mitchellh** [comment]
Slated for 0.2.

**Comment by hholst80** [comment]
I have version 2.0 but I still have the same issue? How do I completely uninstall the software so I get a fresh install experience?

**Comment by hholst80** [comment]
Suggested uninstall process:

1. sudo pkill waypoint
2. docker stop waypoint-server ; docker rm waypoint-server ; docker volume rm waypoint-server
3. rm ~/.config/waypoint 

also, the current directory holds additional configuration so better start with a new directory.

**Comment by briancain** [comment]
@hholst80 - Uninstalling the server will depend on what platform you've installed it to, but since you mention docker:

- docker stop waypoint-server (stop the server container from running)
- docker rm waypoint-server (remove it from docker)
- docker volume rm waypoint-server (note that this will delete any data saved by the server like the token generated during the bootstrap step... so you're ensuring that you start with a fresh volume the next time you install)
- waypoint context delete \<your current server context>

You might not want to completely blow away the config dir like you mentioned in step 2, as you might be using other server contexts for other platforms like nomad or k8s. But if you want to just completely remove everything, then removing that config dir will delete any left over contexts. You can also do this through the waypoint CLI with `waypoint context delete -all` which might be safer going forward.

You should also be good to just remove the local project `.waypoint` directory if you've already destroyed your waypoint project. You shouldn't need to start with a new directory, just remove `.waypoint` from your local project and it will get re-created when you `waypoint init`.

After all that, you should be good to start the install process again to get a fresh server. Note that the uninstall and reinstall process will be automated with a CLI subcommand in a future release for the supported server platforms! :heart:
