### ISSUE TITLE
Running the heroku/buildpacks on top of k8s pods when using a win client?

### ISSUE THREAD

**Issue by talbdev** [hashicorp/waypoint#642]
**Is your feature request related to a problem? Please describe.**
In my organization, we have some developers working with Windows machines, which have kubectl configured to a very large Kubernetes cluster(each developer has its own namespace and certs). When performing waypoint up(waypoint was deployed using --platform=kubernetes of course), waypoint builds the project, however it does it on the local computer(which requires docker engine, we all know docker for windows is BAD), it would be nice if it would run the compiler over a Pod within Kubernetes, that way it would give us a full cloud capabilities for both development and deployment, currently only the deployment processes are performed on Kubernetes or correct me if i'm wrong ? because when i'm trying waypoint up on the win client, waypoint uses the windows docker engine to make the build (-vvv clearly shows that).

**Describe the solution you'd like**
Run the build and entire heroku/buildpacks on k8s pods while building the project - will require a way to transfer the code to the pod prior to code compilation process.

**Comment by mitchellh** [comment]
I believe this will eventually be resolved with [remote runners](https://www.waypointproject.io/docs/roadmap#remote-runners) which are on the roadmap and will come soon. Since it is already on the roadmap I will close this issue. In the remote runner world, your developers can use the Waypoint CLI but the running could happen in your K8S cluster.
