### ISSUE TITLE
Configure a custom repository for waypoint to pull images from

### ISSUE THREAD

**Issue by batman-that-laughs** [hashicorp/waypoint#675]
**Is your feature request related to a problem? Please describe.**
I have a custom registry in use for docker to communicate with public repositories.

**Describe the solution you'd like**
Configure a custom repository for waypoint to pull images from.
The host system doesn't have internet access, however we do have a mirror to communicate with public repositories. We were wondering if we could configure a mirror/ custom repository for waypoint to communicate with the public repositories.

if this is a configurable option in waypoint, could you guide me so as to how to go about it..
also is there another way of achieving this?

thanks!

**Comment by mitchellh** [comment]
How would you do this normally with Docker? This is a usage style with Docker I’m unfamiliar with but seeing how it would work with Docker may help guide me to how it’d work with WP.

**Comment by batman-that-laughs** [comment]
hi,

sorry for not being able to explain it properly, may be the diagram will help...

![docker](https://user-images.githubusercontent.com/55573776/96964783-b2f1d380-1528-11eb-932f-56c5c4b99be4.JPG)

normally how we use is:
docker pull custom-registry/image:tag
docker tag custom-registry/image:tag image:tag

hoping that the tool will pick the image from the host registry.
but currently waypoint is trying to pull the heroku/buildpacks:18 from dokcer hub.

can you suggest a way to use the custom registry to pull the heroku image or anyother images that it needs...

**Comment by batman-that-laughs** [comment]
hi, 
any leads on this?

**Comment by briancain** [comment]
Hey there @batman-that-laughs - If you are hoping to use a custom registry for Docker, you should be able to do this today:

The title only mentions pulling, but for a complete picture or for future readers, it should be mentioned that you can also use the build step to push artifacts to a custom container registry. Although this [example is deploying to Kubernetes](https://github.com/hashicorp/waypoint-examples/blob/93ed0e8baf68a0dc641af34c9a81b18556b97a06/kubernetes/nodejs-local-registry/waypoint.hcl#L9-L18), it should apply for any platform you wish to deploy to:

Note that `localhost:5000` could be replaced with the hostname for where your custom registry lives.

```hcl
  build {
    use "pack" {}
    registry {
      use "docker" {
        image = "localhost:5000/example-nodejs"
        tag   = "1"
        local = false
      }
    }
  }
```

Now if you're just hoping to pull from a private registry. you would instead replace the `use "docker" {}` stanza and use the [docker-pull](https://www.waypointproject.io/plugins/docker#docker-pull-builder) plugin.

```hcl
build {
  use "docker-pull" {
    image = "gcr.io/my-project/my-image"
    tag   = "abcd1234"
  }
}
```

Replace the URL here with the hostname of your registry, and instead of building an artifact, Waypoint will instead pull from your custom registry. Note that Waypoint expects the registry to be configured and managed already, and will use the image hostname as a way to make a request to your custom container registry.

Hopefully that clears things up! If you find any bugs or issues with this plugin please feel free to open a new issue or enhancement request on GitHub. Thank you! 😄

**Comment by batman-that-laughs** [comment]
Hey @briancain thanks for the update!
Will try this!
