### ISSUE TITLE
support groups of apps and defaults for apps and groups

### ISSUE THREAD

**Issue by winmillwill** [hashicorp/waypoint#676]
**Is your feature request related to a problem? Please describe.**
I have an application that is deployed as distinct groups of services for geographical nearness to clients, for compliance reasons, and for isolating failures eg in a staged rollout. To use waypoint, I would (IIUC) need an app for each service in each instance, which would be ~36 app stanzas in my case.

**Describe the solution you'd like**
Provide some way of grouping apps together and some way of providing defaults for groups and apps.

**Describe alternatives you've considered**
- Generating the waypoint config
- Not using waypoint

**Comment by mitchellh** [comment]
Something to solve this general issue will come eventually. We don’t know what shape it will take yet and we don’t have a timeline (but its not 0.2 and probably not 0.3 either). I’ll keep this open for now as an enhancement request but will probably close at some point once we make another issue to track this in more detail.

**Comment by koesbong** [comment]
Hey @winmillwill,

We want to get to your request. However, at the moment, we have a lot more work to do before we are ready to support large multi-app configurations in Waypoint. This means that your request isn't something we can get to in the short term.

Rather than letting this issue linger and grow stale over time, we are going to close it. We so want to assure you that this doesn't mean it will disappear from our radar. We recognize that this is a problem and we hope to tackle it later down the road.

Thank you again for opening the issue.
