### ISSUE TITLE
`waypoint server config-set` sets unspecified parameters back to default

### ISSUE THREAD

**Issue by nickatsegment** [hashicorp/waypoint#686]
**Describe the bug**
(I don't see any way to do a `config-get`, so I'm just deducing from behaviour.)

Unspecified flags to `config-set` will reset values to their defaults, even if they had values before.

**Steps to Reproduce**

1. `waypoint install` a new installation. Do a deploy and see `WAYPOINT_SERVER_ADDR` is set correctly, `WAYPOINT_SERVER_TLS_SKIP_VERIFY=1` and `WAYPOINT_SERVER_TLS=1` (the install defaults).
2. `waypoint server config-set -advertise-tls=false`. Deploy. See that `WAYPOINT_SERVER_DISABLE=1`, and the other values are unset.
3. `waypoint server config-set -advertise-addr=<original addr>`. Deploy. See that `WAYPOINT_SERVER_ADDR` is fixed, but `WAYPOINT_SERVER_TLS=1` (which we disabled in 2; this is the flag's default), and `WAYPOINT_SERVER_TLS_SKIP_VERIFY` is unset (equivalent to `false`, the flag's default).
4. `waypoint server config-set -advertise-addr=<original addr> -advertise-tls=true -advertise-tls-skip-verify=true` to restore sanity. Deploy.

**Expected behavior**
Values should only be modified if they are specified as flags. Unspecified flags should not change anything :)

**Additional context**
Server on EKS. Deploying to ECS on EC2. waypoint v0.1.3.

**Comment by briancain** [comment]
Just a quick investigative note on this issue and why it might be a bit tricky to fix (for future readers and the Waypoint team):

The `waypoint server config-set` command uses protobufs to set these values on the server. The issue here is because our values are stored as a `bool` rather than a `*bool`, currently we don't have a great way to determine when a flag is unset versus explicitly set to false on the server. This is why the behavior is present for options left out when a `config-set` is invoked.

A potential fix here is remedying the issue by updating the values to be `*bool` which would require a lot of changes throughout Waypoint currently.

Thanks @catsby for tracking this issue down! /cc @mitchellh
