### ISSUE TITLE
Plugin request for RedHat Openshift

### ISSUE THREAD

**Issue by HarddriveManoj** [hashicorp/waypoint#785]
In our organization, we are planning to use OpenShift based clusters for app hosting, deployments, and releases.
I was going through the WayPoint documentation and plugins availability from [here](https://www.waypointproject.io/plugins) and found that WayPoint does not have a plugin for OpenShift platform as yet.
We already have HashiCorp Vault implemented with OpenShift and wanted to have a seamless experience using Waypoint without much complex configuration as it would be integrated as part of the framework which would be consumed by multiple in-house projects.
Kindly suggest if this feature request can be considered and provide a tentative timeline by which we can have it so we can plan the PoC accordingly.
I would be more than happy to contribute to this project.

**Comment by jennbriden** [comment]
Hello, we have added an openshift flag for the Kubernetes install. Will you please try that and let us know if it works for you? 

https://www.waypointproject.io/commands/server-install#k8s-openshift

**Comment by briancain** [comment]
Hey there @HarddriveManoj - as Jenn mentioned, the k8s platform has a flag for installing openshift, and it also does some detection to see if the server installed exists inside an openshift cluster. Since it's been a while from when we've heard from you, I'm going to go ahead and close this issue. However if you come back and try with the latest version of Waypoint (current that is 0.2.2 at the time I'm writing this), please feel free to comment on this issue or open a new one. Thanks!

**Comment by HarddriveManoj** [comment]
Thank you @briancain for quick assistance!
