### ISSUE TITLE
Specify custom TLS cert for WP server

### ISSUE THREAD

**Issue by kfh** [hashicorp/waypoint#939]
As mentioned in https://www.waypointproject.io/docs/server/run/production#tls-certs there is no way of specifying our own TLS certs to be used by the WP server. We have been early adopters of WP and love the product and are _eagerly_ waiting for the possibility of using our own certs. It's briefly mentioned that _A future version of Waypoint very soon will fix this limitation_. I haven't seen this addressed in any current tasks, are there any timeline on this ?

**Comment by mitchellh** [comment]
This isn't a very difficult task. I've tagged it for 0.2.x and I think we can do this in a patch release soon. Apologies for the late response a lot of us were out for the holidays.

**Comment by mitchellh** [comment]
I actually have a question for you @kfh: how are you installing the Waypoint server? Are you running manually?

I ask because adding custom cert support for running manually is very easy, whereas adding custom cert support for the installation side is a bit trickier. I think we can do the former in a 0.2.x but unsure about the latter.

**Comment by mitchellh** [comment]
https://github.com/hashicorp/waypoint/pull/951 for `waypoint server run`

**Comment by kfh** [comment]
Unfortunately we are not running it manually. The server runs on _AWS EKS_ and is installed using: 
`waypoint install --platform=kubernetes -accept-tos`

**Comment by mitchellh** [comment]
Roger thank you. #951 still is important as that functionality is needed for `waypoint install` to utilize. We'll look into that next.

**Comment by briancain** [comment]
We've explored the ability to pass in a cert with the install command, each supported platform doesn't have a stable way of storing files. Because you wanted to be protective of your cert, it's best that you accomplish this through the manual server run method provided in #951. Thanks again for reporting this issue! 😄
